# Site settings
title: On Two Feet - A Travelogue
description: "A travel journal written by two indian backpackers."
url: "http://thisdigitallife.github.io"
author:
  name: "Pradyumna Chattopadhyay, Souvik Ghosh"
  url: "http://pradyumnac.github.io"

# Build settings
baseurl: /ontwofeet # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

# For SEO Plugin
twitter:
  username: on2feet
logo: /img/emerald.svg
